FROM golang

RUN apt-get update && apt-get install -y redis-server

RUN curl -L -O -s https://github.com/Masterminds/glide/releases/download/v0.11.0/glide-v0.11.0-linux-amd64.tar.gz && \
    tar xf glide-v0.11.0-linux-amd64.tar.gz && mv linux-amd64/glide ${GOPATH}/bin/glide && \
    rm -rf glide-v0.11.0-linux-amd64.tar.gz linux-amd64

ADD . ${GOPATH}/src/github.com/declantraynor/go-events-service

WORKDIR ${GOPATH}/src/github.com/declantraynor/go-events-service
CMD go test $(glide novendor) -cover ./...
